excluded:
  - .build
  - DerivedData
  - Packages/CppCore

opt_in_rules:
  - closure_body_length
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 120
  error: 150
  ignores_comments: true

file_length:
  warning: 400
  error: 500

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 40
  error: 60

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - x
    - y
    - r
    - g
    - b
    - a
    - i
    - j
    - dt
    - dx
    - dy
    - vx
    - vy
    - w
    - h

type_name:
  max_length:
    warning: 50

nesting:
  type_level: 2
  function_level: 3

reporter: "xcode"
